alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias dnf-up='sudo dnf update --exclude=kernel* && flatpak update -y'
alias apt-up="sudo apt update -y && sudo apt upgrade -y --allow-downgrades && sudo apt autoremove -y && flatpak update -y"
alias dc-pull='sudo docker compose -f /opt/docker/docker-compose.yml pull'
alias dc-up='sudo docker compose -f /opt/docker/docker-compose.yml up -d --remove-orphans'
alias dc-down='sudo docker stop $(sudo docker ps -aq) && sudo docker rm $(sudo docker ps -aq)'
alias please='sudo'
alias yl='yamllint'
alias al='ansible-lint'
alias al='ansible-lint'
alias tailscale_up='sudo tailscale up --accept-routes --shields-up --exit-node=100.69.77.107 --user=$USER'
